name: CI/CD - scraper-bcv

on:
  push:
    tags:
      - "v*"   # Publica en PyPI solo si el tag empieza con v (ej: v1.0.0)
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test & CLI Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install in editable mode + dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # editable + extras de desarrollo
          pip install pytest

      - name: Run tests
        run: pytest -v

      - name: Test CLI (python -m scraper_bcv)
        run: |
          python -m scraper_bcv --log-level INFO

  publish:
    name: Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine check dist/*
          twine upload dist/*
